import { transcribe } from "@/lib/transcribe";
import { R2StorageService } from "@/lib/r2-storage";
import { config } from "../config";
import { generateId } from "@/utils/id";
import { nanoid } from "nanoid";
import * as os from "os";
import * as path from "path";
import * as fs from "fs";
import { detectTrailingSilence, getVADSilenceUntil } from "./audio-utils";
import { ffmpegAsync } from "./ffmpeg";
import { getLastFrameFromVideo } from "./ffmpeg";

/**
 * Filters out transcribed words that are likely noise at the end of the video
 * by matching against the expected script text.
 */
/**
 * Strips spurious words generated by Veo AFTER the expected script ends.
 * Searches from the end for the last expected word.
 */
function cleanupTrailingWords(
  words: any[],
  expectedText: string,
): { words: any[]; trimmedCount: number } {
  const normalizedExpected = expectedText
    .trim()
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter(Boolean);
  if (normalizedExpected.length === 0) return { words, trimmedCount: 0 };

  const lastExpectedWord = normalizedExpected[normalizedExpected.length - 1];

  for (let i = words.length - 1; i >= 0; i--) {
    const word = words[i].word.toLowerCase().replace(/[^\w\s]/g, "");
    if (word === lastExpectedWord) {
      const trimmedCount = words.length - 1 - i;
      if (trimmedCount > 0) {
        console.log(
          `[veo-processor] Trailing cleanup: removed ${trimmedCount} noise word(s) after "${words[i].word}"`,
        );
      }
      return { words: words.slice(0, i + 1), trimmedCount };
    }
  }

  return { words, trimmedCount: 0 };
}

/**
 * Strips spurious words generated by Veo BEFORE the expected script starts.
 *
 * Uses an N-word lookahead to confirm the true anchor: when the first expected
 * word appears in the transcription, we verify that the next LOOKAHEAD_WORDS
 * expected words also follow in order. This prevents false positives when a
 * common word (e.g. "I") appears in both the spurious prefix AND the real script.
 *
 * Example: expected = "I see a lot..."
 *   Transcription:  ["I", "named", "their", "cheek", "I", "see", "a", "lot", ...]
 *   Without lookahead: matches index 0 (wrong — "named" doesn't follow)
 *   With lookahead: index 0 fails (next expected "see" ≠ "named"), index 4 passes ✓
 */
function cleanupLeadingWords(
  words: any[],
  expectedText: string,
): { words: any[]; firstWordStart: number | null; trimmedCount: number } {
  const normalizedExpected = expectedText
    .trim()
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter(Boolean);
  if (normalizedExpected.length === 0)
    return { words, firstWordStart: words[0]?.start ?? null, trimmedCount: 0 };

  // How many consecutive expected words must match to confirm the anchor
  const LOOKAHEAD_WORDS = Math.min(3, normalizedExpected.length);
  const firstExpectedWord = normalizedExpected[0];

  for (let i = 0; i < words.length; i++) {
    const word = words[i].word.toLowerCase().replace(/[^\w\s]/g, "");
    if (word !== firstExpectedWord) continue;

    // Verify the next LOOKAHEAD_WORDS - 1 expected words also align
    let matchCount = 1;
    for (let k = 1; k < LOOKAHEAD_WORDS; k++) {
      const nextTranscribedWord = words[i + k]?.word.toLowerCase().replace(/[^\w\s]/g, "");
      const nextExpectedWord = normalizedExpected[k];
      if (nextTranscribedWord === nextExpectedWord) {
        matchCount++;
      } else {
        break;
      }
    }

    if (matchCount >= LOOKAHEAD_WORDS) {
      // Confirmed anchor: this is where the real script starts
      if (i > 0) {
        console.log(
          `[veo-processor] Leading cleanup: removed ${i} spurious word(s) before "${words[i].word}" (starts at ${words[i].start.toFixed(3)}s)`,
        );
      }
      return { words: words.slice(i), firstWordStart: words[i].start ?? null, trimmedCount: i };
    }
    // Lookahead failed at this position — keep searching
  }

  // Real start never confirmed — return everything unchanged
  return { words, firstWordStart: words[0]?.start ?? null, trimmedCount: 0 };
}

function cleanupTranscriptionWords(
  words: any[],
  expectedText: string,
): { words: any[]; firstWordStart: number | null } {
  const leading = cleanupLeadingWords(words, expectedText);
  const trailing = cleanupTrailingWords(leading.words, expectedText);
  // Only expose firstWordStart when spurious leading words were actually found and removed.
  // If no leading words were stripped, the silence before speech is natural and VAD already handles it.
  const firstWordStart = leading.trimmedCount > 0 ? leading.firstWordStart : null;
  return { words: trailing.words, firstWordStart };
}

async function processTranscription(rawR2Url: string, expectedText?: string) {
  const result = await transcribe({ url: rawR2Url });

  const offsetSeconds = (result as any).offsetSeconds || 0;
  const endOffsetSeconds = (result as any).endOffsetSeconds || 0;

  let lastWordEnd: number | null = null;
  let firstWordStart: number | null = null;
  let words = result?.results?.main?.words ?? [];

  if (expectedText && words.length > 0) {
    const cleaned = cleanupTranscriptionWords(words, expectedText);
    words = cleaned.words;
    // firstWordStart is non-null only when cleanupLeadingWords actually stripped spurious words
    // from the front. No expectedText means we can't distinguish spurious from real words.
    firstWordStart = cleaned.firstWordStart;
  }

  if (words.length > 0) {
    // Primary source: get the absolute last word timestamp from the transcription results
    lastWordEnd = Math.max(...words.map((w: any) => w.end as number));
  } else if (endOffsetSeconds > 0) {
    // Fallback: use endOffsetSeconds if words are somehow missing but offset was provided
    lastWordEnd = endOffsetSeconds;
  }

  return { offsetSeconds, lastWordEnd, firstWordStart };
}

async function applySilenceAndTrim(
  localRawPath: string,
  offsetSeconds: number,
  lastWordEnd: number | null,
  actualDuration: number,
  tempDir: string,
): Promise<Buffer> {
  console.log({ offsetSeconds, lastWordEnd, actualDuration });
  const outputPath = path.join(tempDir, `trimmed-${nanoid()}.mp4`);
  const audioFilters = [];

  if (offsetSeconds > 0) {
    // divide by 1.25 for safety
    audioFilters.push(`volume=enable='between(t,0,${offsetSeconds / 1.25})':volume=0`);
  }

  if (lastWordEnd && lastWordEnd > 0) {
    // Mute everything after the last word (+0.1s natural decay buffer) to create a perfectly clean pause
    const muteStart = (lastWordEnd + 0.1).toFixed(3);
    audioFilters.push(`volume=enable='between(t,${muteStart},9999)':volume=0`);
  }

  const ffmpegArgs = ["-y", "-i", localRawPath, "-t", actualDuration.toString()];

  if (audioFilters.length > 0) {
    ffmpegArgs.push("-af", audioFilters.join(","), "-c:v", "copy", "-c:a", "aac");
  } else {
    ffmpegArgs.push("-c", "copy");
  }

  ffmpegArgs.push(outputPath);
  await ffmpegAsync(ffmpegArgs);

  if (!fs.existsSync(outputPath)) {
    throw new Error("Trimmed video was not generated.");
  }

  const trimmedBuf = fs.readFileSync(outputPath);
  fs.unlinkSync(outputPath);
  return trimmedBuf;
}

/**
 * Transcribes a Veo-generated video via Deepgram, calculates the actual
 * spoken duration from the last word timestamp, trims the video exactly to
 * that duration (lastWordEnd + 0.3 s padding), and returns the trimmed URL.
 *
 * No reference/estimated duration is used — the truth comes entirely from
 * the transcription.
 */
export async function transcribeAndTrimVeoVideo({
  rawR2Url,
  schemaId,
  segmentId,
  expectedText,
}: {
  rawR2Url: string;
  schemaId: string;
  segmentId: string;
  expectedText?: string;
}): Promise<{
  finalR2Url: string;
  lastFrameUrl?: string;
  tsUrl?: string;
  actualDuration: number;
  comparison: { original: string; updated: string };
}> {
  const r2 = new R2StorageService({
    bucketName: config.r2.bucket,
    accessKeyId: config.r2.accessKeyId,
    secretAccessKey: config.r2.secretAccessKey,
    accountId: config.r2.accountId,
    cdn: config.r2.cdn,
  });

  // 1. Transcribe raw video to get timings for cleanup and trim decisions
  let transcription;
  try {
    transcription = await processTranscription(rawR2Url, expectedText);
  } catch (e) {
    console.error(`Transcription failed for ${segmentId}:`, e);
  }

  // 2. Validate transcription words found
  if (!transcription || transcription.lastWordEnd === null) {
    console.warn(`[veo-processor] No words found for ${segmentId}, keeping raw video untrimmed.`);
    return {
      finalR2Url: rawR2Url,
      tsUrl: undefined,
      actualDuration: 0,
      comparison: { original: rawR2Url, updated: rawR2Url },
    };
  }

  // 3. Download raw video locally for analysis
  const tempDir = os.tmpdir();
  const localRawPath = path.join(tempDir, `raw-${nanoid()}.mp4`);

  try {
    const fetchRes = await fetch(rawR2Url);
    fs.writeFileSync(localRawPath, Buffer.from(await fetchRes.arrayBuffer()));

    // 4. Calculate actual duration (adaptive silence gap)
    const actualDuration = await detectTrailingSilence(localRawPath, transcription.lastWordEnd, {
      minGap: 0.1,
      buffer: 0.1,
      aggressiveFallback: 0.1,
    });
    console.log(
      `[veo-processor] Calculated actual duration ${actualDuration?.toFixed(3)}s for ${segmentId}`,
    );

    // 5. Apply intro silence and end trim via FFMPEG
    const vadOffset = await getVADSilenceUntil(rawR2Url);

    // Pick the best intro-silence offset from 3 sources:
    // - VAD (voice activity detection — most precise)
    // - firstWordStart from transcription (reliable fallback if VAD misses leading noise words)
    // - Deepgram offsetSeconds (least likely to be accurate but present as last resort)
    // We take the MAX, because if the transcription first word starts late, the intro is at least that long.
    const firstWordOffset = transcription.firstWordStart ?? 0;
    const deepgramOffset = transcription.offsetSeconds ?? 0;
    const introSilenceOffset = Math.max(vadOffset ?? 0, firstWordOffset, deepgramOffset);
    console.log(
      `[veo-processor] Intro silence offset: ${introSilenceOffset.toFixed(3)}s (VAD: ${vadOffset?.toFixed(3) ?? "N/A"}, firstWord: ${firstWordOffset.toFixed(3)}s, Deepgram: ${deepgramOffset.toFixed(3)}s) for ${segmentId}`,
    );

    const trimmedBuf = await applySilenceAndTrim(
      localRawPath,
      introSilenceOffset,
      transcription.lastWordEnd,
      actualDuration!,
      tempDir,
    );

    // 6. Upload cleanly trimmed video to R2
    const trimmedFileName = `ugc-videos/${schemaId}/${segmentId}/trimmed-${nanoid()}.mp4`;
    const finalVideoUrl = await r2.uploadData(trimmedFileName, trimmedBuf, "video/mp4");

    // 7. Extract last frame from trimmed buffer (already in memory — no re-download needed)
    let lastFrameUrl: string | undefined;
    try {
      const tempTrimmedPath = path.join(tempDir, `trimmed-frame-src-${nanoid()}.mp4`);
      fs.writeFileSync(tempTrimmedPath, trimmedBuf);
      try {
        const lastFrameBuffer = await getLastFrameFromVideo(tempTrimmedPath, tempDir);
        const lastFrameR2Name = `ugc-videos/${schemaId}/${segmentId}/last-frame-${nanoid()}.png`;
        lastFrameUrl = await r2.uploadData(lastFrameR2Name, lastFrameBuffer, "image/png");
      } finally {
        if (fs.existsSync(tempTrimmedPath)) fs.unlinkSync(tempTrimmedPath);
      }
    } catch (e) {
      console.warn(`[veo-processor] Last frame extraction failed for ${segmentId}:`, e);
    }

    if (fs.existsSync(localRawPath)) fs.unlinkSync(localRawPath);

    // 8. Re-transcribe the trimmed video for accurate final timestamps
    //    The raw transcription timestamps shift after intro silence removal and end-trim,
    //    so we need a fresh transcription from the clean output.
    let finalTsUrl: string | undefined;
    try {
      const finalResult = await transcribe({ url: finalVideoUrl });
      finalTsUrl = await r2.uploadData(
        `transcriptions/${schemaId}/${segmentId}/${generateId()}.json`,
        Buffer.from(JSON.stringify(finalResult)),
        "application/json",
      );
    } catch (e) {
      console.warn(
        `[veo-processor] Re-transcription of trimmed video failed for ${segmentId}, tsUrl will be undefined:`,
        e,
      );
    }

    return {
      finalR2Url: finalVideoUrl,
      lastFrameUrl,
      tsUrl: finalTsUrl,
      actualDuration: actualDuration!,
      comparison: { original: rawR2Url, updated: finalVideoUrl },
    };
  } catch (err) {
    console.error(`Failed to trim video for segment ${segmentId}:`, err);
    if (fs.existsSync(localRawPath)) fs.unlinkSync(localRawPath);

    // Fall back to the raw video but still return duration estimate
    return {
      finalR2Url: rawR2Url,
      tsUrl: undefined,
      actualDuration: transcription.lastWordEnd + 0.3,
      comparison: { original: rawR2Url, updated: rawR2Url },
    };
  }
}
