import { transcribe } from "@/lib/transcribe";
import { R2StorageService } from "@/lib/r2-storage";
import { TtsService } from "@/lib/tts";
import { config } from "../config";
import { generateId } from "@/utils/id";
import { nanoid } from "nanoid";
import * as os from "os";
import * as path from "path";
import * as fs from "fs";
import { execSync } from "child_process";
import { ffprobeStatic } from "@/utils/ffmpeg-config";
import { detectTrailingSilence } from "./audio-utils";
import { ffmpegAsync } from "./ffmpeg";
import { getLastFrameFromVideo } from "./ffmpeg";

/**
 * Filters out transcribed words that are likely noise at the end of the video
 * by matching against the expected script text.
 */
/**
 * Strips spurious words generated by Veo AFTER the expected script ends.
 * Searches from the end for the last expected word.
 */
function cleanupTrailingWords(
  words: any[],
  expectedText: string,
): { words: any[]; trimmedCount: number } {
  const normalizedExpected = expectedText
    .trim()
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter(Boolean);
  if (normalizedExpected.length === 0) return { words, trimmedCount: 0 };

  const lastExpectedWord = normalizedExpected[normalizedExpected.length - 1];

  for (let i = words.length - 1; i >= 0; i--) {
    const word = words[i].word.toLowerCase().replace(/[^\w\s]/g, "");
    if (word === lastExpectedWord) {
      const trimmedCount = words.length - 1 - i;
      if (trimmedCount > 0) {
        console.log(
          `[veo-processor] Trailing cleanup: removed ${trimmedCount} noise word(s) after "${words[i].word}"`,
        );
      }
      return { words: words.slice(0, i + 1), trimmedCount };
    }
  }

  return { words, trimmedCount: 0 };
}

/**
 * Strips spurious words generated by Veo BEFORE the expected script starts.
 *
 * Uses an N-word lookahead to confirm the true anchor: when the first expected
 * word appears in the transcription, we verify that the next LOOKAHEAD_WORDS
 * expected words also follow in order. This prevents false positives when a
 * common word (e.g. "I") appears in both the spurious prefix AND the real script.
 *
 * Example: expected = "I see a lot..."
 *   Transcription:  ["I", "named", "their", "cheek", "I", "see", "a", "lot", ...]
 *   Without lookahead: matches index 0 (wrong — "named" doesn't follow)
 *   With lookahead: index 0 fails (next expected "see" ≠ "named"), index 4 passes ✓
 */
function cleanupLeadingWords(
  words: any[],
  expectedText: string,
): { words: any[]; firstWordStart: number | null; trimmedCount: number } {
  const normalizedExpected = expectedText
    .trim()
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .split(/\s+/)
    .filter(Boolean);
  if (normalizedExpected.length === 0)
    return { words, firstWordStart: words[0]?.start ?? null, trimmedCount: 0 };

  // How many consecutive expected words must match to confirm the anchor
  const LOOKAHEAD_WORDS = Math.min(3, normalizedExpected.length);
  const firstExpectedWord = normalizedExpected[0];

  for (let i = 0; i < words.length; i++) {
    const word = words[i].word.toLowerCase().replace(/[^\w\s]/g, "");
    if (word !== firstExpectedWord) continue;

    // Verify the next LOOKAHEAD_WORDS - 1 expected words also align
    let matchCount = 1;
    for (let k = 1; k < LOOKAHEAD_WORDS; k++) {
      const nextTranscribedWord = words[i + k]?.word.toLowerCase().replace(/[^\w\s]/g, "");
      const nextExpectedWord = normalizedExpected[k];
      if (nextTranscribedWord === nextExpectedWord) {
        matchCount++;
      } else {
        break;
      }
    }

    if (matchCount >= LOOKAHEAD_WORDS) {
      // Confirmed anchor: this is where the real script starts
      if (i > 0) {
        console.log(
          `[veo-processor] Leading cleanup: removed ${i} spurious word(s) before "${words[i].word}" (starts at ${words[i].start.toFixed(3)}s)`,
        );
      }
      return { words: words.slice(i), firstWordStart: words[i].start ?? null, trimmedCount: i };
    }
    // Lookahead failed at this position — keep searching
  }

  // Real start never confirmed — return everything unchanged
  return { words, firstWordStart: words[0]?.start ?? null, trimmedCount: 0 };
}

function cleanupTranscriptionWords(
  words: any[],
  expectedText: string,
): { words: any[]; firstWordStart: number | null } {
  const leading = cleanupLeadingWords(words, expectedText);
  const trailing = cleanupTrailingWords(leading.words, expectedText);
  // Only expose firstWordStart when spurious leading words were actually found and removed.
  // If no leading words were stripped, the silence before speech is natural.
  const firstWordStart = leading.trimmedCount > 0 ? leading.firstWordStart : null;
  return { words: trailing.words, firstWordStart };
}

async function processTranscription(rawR2Url: string, expectedText?: string) {
  const result = await transcribe({ url: rawR2Url });

  const offsetSeconds = (result as any).offsetSeconds || 0;
  const endOffsetSeconds = (result as any).endOffsetSeconds || 0;

  let lastWordEnd: number | null = null;
  let firstWordStart: number | null = null;
  let words = result?.results?.main?.words ?? [];

  if (expectedText && words.length > 0) {
    const cleaned = cleanupTranscriptionWords(words, expectedText);
    words = cleaned.words;
    firstWordStart = cleaned.firstWordStart;
  }

  if (words.length > 0) {
    lastWordEnd = Math.max(...words.map((w: any) => w.end as number));
  } else if (endOffsetSeconds > 0) {
    lastWordEnd = endOffsetSeconds;
  }

  return { offsetSeconds, lastWordEnd, firstWordStart };
}

async function applySilenceAndTrim(
  localRawPath: string,
  offsetSeconds: number,
  lastWordEnd: number | null,
  actualDuration: number,
  tempDir: string,
): Promise<Buffer> {
  console.log({ offsetSeconds, lastWordEnd, actualDuration });
  const outputPath = path.join(tempDir, `trimmed-${nanoid()}.mp4`);
  const audioFilters = [];

  if (offsetSeconds > 0) {
    // divide by 1.25 for safety
    audioFilters.push(`volume=enable='between(t,0,${offsetSeconds / 1.25})':volume=0`);
  }

  if (lastWordEnd && lastWordEnd > 0) {
    // Mute everything after the last word (+0.1s natural decay buffer)
    const muteStart = (lastWordEnd + 0.1).toFixed(3);
    audioFilters.push(`volume=enable='between(t,${muteStart},9999)':volume=0`);
  }

  const ffmpegArgs = ["-y", "-i", localRawPath, "-t", actualDuration.toString()];

  if (audioFilters.length > 0) {
    ffmpegArgs.push("-af", audioFilters.join(","), "-c:v", "copy", "-c:a", "aac");
  } else {
    ffmpegArgs.push("-c", "copy");
  }

  ffmpegArgs.push(outputPath);
  await ffmpegAsync(ffmpegArgs);

  if (!fs.existsSync(outputPath)) {
    throw new Error("Trimmed video was not generated.");
  }

  const trimmedBuf = fs.readFileSync(outputPath);
  fs.unlinkSync(outputPath);
  return trimmedBuf;
}

/**
 * Gets audio duration in milliseconds from a local file using ffprobe.
 */
function getAudioDurationMs(filePath: string): number {
  try {
    const out = execSync(
      `"${ffprobeStatic}" -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${filePath}"`,
    ).toString();
    return parseFloat(out.trim()) * 1000;
  } catch {
    return 0;
  }
}

/**
 * Transcribes a Veo-generated video via Deepgram, calculates the actual
 * spoken duration from the last word timestamp, trims the video exactly to
 * that duration (lastWordEnd + 0.3 s padding), and returns the trimmed URL.
 *
 * Audio is first isolated via ElevenLabs to remove Veo-generated background
 * noise before transcription and trimming. VAD is no longer used.
 */
export async function transcribeAndTrimVeoVideo({
  rawR2Url,
  schemaId,
  segmentId,
  expectedText,
  tts,
}: {
  rawR2Url: string;
  schemaId: string;
  segmentId: string;
  expectedText?: string;
  tts: TtsService;
}): Promise<{
  finalR2Url: string;
  isolatedVideoUrl?: string;
  lastFrameUrl?: string;
  tsUrl?: string;
  actualDuration: number;
  comparison: { original: string; updated: string };
}> {
  const r2 = new R2StorageService({
    bucketName: config.r2.bucket,
    accessKeyId: config.r2.accessKeyId,
    secretAccessKey: config.r2.secretAccessKey,
    accountId: config.r2.accountId,
    cdn: config.r2.cdn,
  });

  const tempDir = os.tmpdir();
  const localRawPath = path.join(tempDir, `raw-${nanoid()}.mp4`);
  const rawAudioPath = path.join(tempDir, `audio-${nanoid()}.mp3`);
  const paddedAudioPath = path.join(tempDir, `padded-${nanoid()}.mp3`);
  const cleanAudioPath = path.join(tempDir, `clean-${nanoid()}.mp3`);
  const cleanVideoPath = path.join(tempDir, `clean-video-${nanoid()}.mp4`);

  // Tracks whether ElevenLabs isolation succeeded, to decide intro offset strategy
  let isolationSucceeded = false;

  try {
    // 1. Download raw video
    const fetchRes = await fetch(rawR2Url);
    fs.writeFileSync(localRawPath, Buffer.from(await fetchRes.arrayBuffer()));

    // 2. Isolate voice via ElevenLabs and merge clean audio back into video
    let localVideoPath = localRawPath;
    let isolatedVideoUrl: string | undefined = undefined;
    try {
      // 2a. Extract audio track as mp3
      await ffmpegAsync([
        "-y",
        "-i",
        localRawPath,
        "-vn",
        "-acodec",
        "libmp3lame",
        "-ab",
        "128k",
        rawAudioPath,
      ]);

      // 2b. Pad to 5s minimum if needed (ElevenLabs audio isolation minimum)
      const audioDurationMs = getAudioDurationMs(rawAudioPath);
      let audioToIsolatePath = rawAudioPath;
      if (audioDurationMs > 0 && audioDurationMs < 5000) {
        await ffmpegAsync([
          "-y",
          "-i",
          rawAudioPath,
          "-af",
          "apad,atrim=0:5",
          "-to",
          "5",
          paddedAudioPath,
        ]);
        audioToIsolatePath = paddedAudioPath;
        console.log(
          `[veo-processor] Audio padded to 5s for isolation (was ${(audioDurationMs / 1000).toFixed(2)}s) for ${segmentId}`,
        );
      }

      // 2c. Isolate voice using ElevenLabs (removes background noise, music, SFX)
      const rawAudioBuffer = fs.readFileSync(audioToIsolatePath);
      const cleanAudioBuffer = await tts.isolateAudio(rawAudioBuffer);
      fs.writeFileSync(cleanAudioPath, cleanAudioBuffer);
      console.log(`[veo-processor] ElevenLabs isolation complete for ${segmentId}`);

      // 2d. Merge isolated audio back into the original video
      await ffmpegAsync([
        "-y",
        "-i",
        localRawPath,
        "-i",
        cleanAudioPath,
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-c:v",
        "copy",
        "-c:a",
        "aac",
        "-shortest",
        cleanVideoPath,
      ]);

      localVideoPath = cleanVideoPath;
      isolationSucceeded = true;

      // Upload the isolated video so we can transcribe the cleaned audio remotely
      const cleanBuf = fs.readFileSync(cleanVideoPath);
      isolatedVideoUrl = await r2.uploadData(
        `ugc-videos/${schemaId}/${segmentId}/isolated-${nanoid()}.mp4`,
        cleanBuf,
        "video/mp4",
      );
    } catch (e) {
      console.warn(
        `[veo-processor] Voice isolation failed for ${segmentId}, continuing with raw audio:`,
        e,
      );
    } finally {
      [rawAudioPath, paddedAudioPath, cleanAudioPath].forEach((p) => {
        if (fs.existsSync(p)) fs.unlinkSync(p);
      });
    }

    // 3. Transcribe the (now clean) video
    let transcription;
    try {
      const transcribeUrl = isolationSucceeded && isolatedVideoUrl ? isolatedVideoUrl : rawR2Url;
      transcription = await processTranscription(transcribeUrl, expectedText);
    } catch (e) {
      console.error(`Transcription failed for ${segmentId}:`, e);
    }

    // 4. Validate transcription
    if (!transcription || transcription.lastWordEnd === null) {
      console.warn(`[veo-processor] No words found for ${segmentId}, keeping video untrimmed.`);
      if (fs.existsSync(localRawPath)) fs.unlinkSync(localRawPath);
      if (fs.existsSync(cleanVideoPath)) fs.unlinkSync(cleanVideoPath);
      return {
        finalR2Url: rawR2Url,
        isolatedVideoUrl,
        tsUrl: undefined,
        actualDuration: 0,
        comparison: { original: rawR2Url, updated: rawR2Url },
      };
    }

    // 5. Calculate actual duration (adaptive silence gap from last spoken word)
    const actualDuration = await detectTrailingSilence(localVideoPath, transcription.lastWordEnd, {
      minGap: 0.1,
      buffer: 0.1,
      aggressiveFallback: 0.1,
    });
    console.log(
      `[veo-processor] Calculated actual duration ${actualDuration?.toFixed(3)}s for ${segmentId}`,
    );

    // 6. Determine intro silence offset for trimming
    // If isolation succeeded, ElevenLabs already removed the leading noise — no muting needed.
    // If isolation failed, fall back to using transcription timestamps.
    const firstWordOffset = transcription.firstWordStart ?? 0;
    const deepgramOffset = transcription.offsetSeconds ?? 0;
    const introSilenceOffset = isolationSucceeded ? 0 : Math.max(firstWordOffset, deepgramOffset);

    console.log(
      `[veo-processor] Intro offset: ${introSilenceOffset.toFixed(3)}s (isolation: ${isolationSucceeded}, firstWord: ${firstWordOffset.toFixed(3)}s, Deepgram: ${deepgramOffset.toFixed(3)}s) for ${segmentId}`,
    );

    // 7. Apply end trim via ffmpeg
    const trimmedBuf = await applySilenceAndTrim(
      localVideoPath,
      introSilenceOffset,
      transcription.lastWordEnd,
      actualDuration!,
      tempDir,
    );

    // 8. Upload trimmed video to R2
    const trimmedFileName = `ugc-videos/${schemaId}/${segmentId}/trimmed-${nanoid()}.mp4`;
    const finalVideoUrl = await r2.uploadData(trimmedFileName, trimmedBuf, "video/mp4");

    // 9. Extract last frame from trimmed buffer
    let lastFrameUrl: string | undefined;
    try {
      const tempTrimmedPath = path.join(tempDir, `trimmed-frame-src-${nanoid()}.mp4`);
      fs.writeFileSync(tempTrimmedPath, trimmedBuf);
      try {
        const lastFrameBuffer = await getLastFrameFromVideo(tempTrimmedPath, tempDir);
        const lastFrameR2Name = `ugc-videos/${schemaId}/${segmentId}/last-frame-${nanoid()}.png`;
        lastFrameUrl = await r2.uploadData(lastFrameR2Name, lastFrameBuffer, "image/png");
      } finally {
        if (fs.existsSync(tempTrimmedPath)) fs.unlinkSync(tempTrimmedPath);
      }
    } catch (e) {
      console.warn(`[veo-processor] Last frame extraction failed for ${segmentId}:`, e);
    }

    // 10. Cleanup local files
    if (fs.existsSync(localRawPath)) fs.unlinkSync(localRawPath);
    if (fs.existsSync(cleanVideoPath)) fs.unlinkSync(cleanVideoPath);

    // 11. Re-transcribe trimmed video for accurate final timestamps
    let finalTsUrl: string | undefined;
    try {
      const finalResult = await transcribe({ url: finalVideoUrl });
      finalTsUrl = await r2.uploadData(
        `transcriptions/${schemaId}/${segmentId}/${generateId()}.json`,
        Buffer.from(JSON.stringify(finalResult)),
        "application/json",
      );
    } catch (e) {
      console.warn(
        `[veo-processor] Re-transcription of trimmed video failed for ${segmentId}, tsUrl will be undefined:`,
        e,
      );
    }

    return {
      finalR2Url: finalVideoUrl,
      isolatedVideoUrl,
      lastFrameUrl,
      tsUrl: finalTsUrl,
      actualDuration: actualDuration!,
      comparison: { original: rawR2Url, updated: isolatedVideoUrl || finalVideoUrl },
    };
  } catch (err) {
    console.error(`Failed to process video for segment ${segmentId}:`, err);

    // Cleanup any leftover temp files
    [localRawPath, cleanVideoPath].forEach((p) => {
      if (fs.existsSync(p)) fs.unlinkSync(p);
    });

    return {
      finalR2Url: rawR2Url,
      isolatedVideoUrl: undefined,
      tsUrl: undefined,
      actualDuration: 0,
      comparison: { original: rawR2Url, updated: rawR2Url },
    };
  }
}
