export const MUSIC = [
  {
    id: "music-1",
    name: "Inspirational Uplifting Calm Piano",
    author: "NikitaKondrashev",
    url: "https://cdn.designcombo.dev/music/audio_aa8bbcdd47.mp3",
    category: "music",
    genre: "modern classical",
    duration: 104,
    alt: "Quiet, Soft, Piano, Relax, Piano Music",
  },
  {
    id: "music-2",
    name: "The Cradle of Your Soul",
    author: "lemonmusicstudio",
    url: "https://cdn.designcombo.dev/music/audio_d0c6ff1bdd.mp3",
    category: "music",
    genre: "solo guitar",
    duration: 177,
    alt: "Acoustic Guitar, Calm, Inspiring, Easy",
  },
  {
    id: "music-3",
    name: "Endless by PrabajithK",
    author: "MildRelaxation",
    url: "https://cdn.designcombo.dev/music/audio_7e44a45464.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 640,
    alt: "Please support us for more copyright-free music tracks.",
  },
  {
    id: "music-4",
    name: "peace of mind - Calm Ambient Music",
    author: "Clavier-Music",
    url: "https://cdn.designcombo.dev/music/audio_7cc1e69569.mp3",
    category: "music",
    genre: "ambient",
    duration: 113,
    alt: "Ambient, Calm, Music, Calm Music",
  },
  {
    id: "music-5",
    name: "Wide Flower Fields (Atmospheric Ambient)",
    author: "AudioCoffee",
    url: "https://cdn.designcombo.dev/music/audio_a37120f89e.mp3",
    category: "music",
    genre: "ambient",
    duration: 245,
    alt: "Ambient, Ambient Background",
  },
  {
    id: "music-6",
    name: "Smooth Waters",
    author: "SergePavkinMusic",
    url: "https://cdn.designcombo.dev/music/audio_0fea22d728.mp3",
    category: "music",
    genre: "beautiful plays",
    duration: 299,
    alt: "Link to the track in the Facebook/Instagram audio library: https://www.instagram.com/reels/audio/519843260336291/",
  },
  {
    id: "music-7",
    name: "Coniferous forest",
    author: "orangery",
    url: "https://cdn.designcombo.dev/music/audio_676747013a.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 128,
    alt: "Acoustic, Guitar",
  },
  {
    id: "music-8",
    name: "In the Forest - Ambient Acoustic Guitar Instrumental Background Music For Videos",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_202082aa0b.mp3",
    category: "music",
    genre: "solo guitar",
    duration: 119,
    alt: "",
  },
  {
    id: "music-9",
    name: "Cinematic Fairy Tale Story (Main)",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_153f263349.mp3",
    category: "music",
    genre: "main title",
    duration: 127,
    alt: "Airy, Background, Beautiful Piano, Calm",
  },
  {
    id: "music-10",
    name: "Relaxing Music",
    author: "RelaxingTime",
    url: "https://cdn.designcombo.dev/music/audio_eacbcf15ac.mp3",
    category: "music",
    genre: "ambient",
    duration: 1324,
    alt: "Relax, Ambient, New Age, Chillout",
  },
  {
    id: "music-11",
    name: "Nocturne Piano Music",
    author: "Sakartvelo",
    url: "https://cdn.designcombo.dev/music/audio_c1f13450e1.mp3",
    category: "music",
    genre: "modern classical",
    duration: 186,
    alt: "Piano, Piano Music, Relax, Calm, Soft",
  },
  {
    id: "music-12",
    name: "Summer Rain Melody. Background for meditation and yoga 43 second",
    author: "White_Records",
    url: "https://cdn.designcombo.dev/music/audio_40be26e833.mp3",
    category: "music",
    genre: "ambient",
    duration: 43,
    alt: "Meditation Music, Relaxation Music",
  },
  {
    id: "music-13",
    name: "Peaceful Piano Background Music",
    author: "nickpanek620",
    url: "https://cdn.designcombo.dev/music/audio_c4397b8dad.mp3",
    category: "music",
    genre: "modern classical",
    duration: 207,
    alt: "Background, Background Music, Peaceful",
  },
  {
    id: "music-14",
    name: "China Chinese Asian Music",
    author: "lkoliks",
    url: "https://cdn.designcombo.dev/music/audio_53692c3048.mp3",
    category: "music",
    genre: "world",
    duration: 150,
    alt: "China, Chinese, Asian, Music",
  },
  {
    id: "music-15",
    name: "Legacy of Brahms. Lullaby. Background Orchestral music for video. Full",
    author: "White_Records",
    url: "https://cdn.designcombo.dev/music/audio_10a080e445.mp3",
    category: "music",
    genre: "lullabies",
    duration: 92,
    alt: "Xmas, Xmas Music, Lullaby, Background",
  },
  {
    id: "music-16",
    name: "Sweet Serenade",
    author: "Neura-Flow",
    url: "https://cdn.designcombo.dev/music/audio_52c3ae306a.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 160,
    alt: "Romantic, Acoustic, Love, Song",
  },
  {
    id: "music-17",
    name: "Peaceful Garden - Healing Light Piano for meditation, zen, landscapes",
    author: "HarumachiMusic",
    url: "https://cdn.designcombo.dev/music/audio_b79a40aa49.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 179,
    alt: "Healing, Landscape, Movie, Calm Down",
  },
  {
    id: "music-18",
    name: "peaceful relaxing piano music",
    author: "Clavier-Music",
    url: "https://cdn.designcombo.dev/music/audio_2424b6e004.mp3",
    category: "music",
    genre: "modern classical",
    duration: 243,
    alt: "Calm, Soft, Piano, Relax, Piano Music",
  },
  {
    id: "music-19",
    name: "Celestial Prayer Heavenly Meditation Peaceful Music",
    author: "Denis-Pavlov-Music",
    url: "https://cdn.designcombo.dev/music/audio_dffe86ff81.mp3",
    category: "music",
    genre: "ambient",
    duration: 695,
    alt: "Music, Piano, Prayer, Meditation",
  },
  {
    id: "music-20",
    name: "Inspiring Motivational Mood",
    author: "Alex_MakeMusic",
    url: "https://cdn.designcombo.dev/music/audio_8177755b67.mp3",
    category: "music",
    genre: "beats",
    duration: 138,
    alt: "Music For Videos",
  },
  {
    id: "music-21",
    name: "Beauty of Nature",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_c7d3915f8d.mp3",
    category: "music",
    genre: "main title",
    duration: 66,
    alt: "Beauty Of Nature, Soft Background Music",
  },
  {
    id: "music-22",
    name: "An Eye for Details",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_c43abdd415.mp3",
    category: "music",
    genre: "ambient",
    duration: 67,
    alt: "Arpeggio, Soft Marimba, Background Music",
  },
  {
    id: "music-23",
    name: "Magical Eden",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_69b40fb9d3.mp3",
    category: "music",
    genre: "modern classical",
    duration: 176,
    alt: "Ambient, Calm, Piano, Inspirational",
  },
  {
    id: "music-24",
    name: "Birds of Prey",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_7e31f5d02f.mp3",
    category: "music",
    genre: "ambient",
    duration: 67,
    alt: "Soft, Background, Birds, Birds Of Prey",
  },
  {
    id: "music-25",
    name: "Perfect Beauty",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_b9bc3934cc.mp3",
    category: "music",
    genre: "pulses",
    duration: 440,
    alt: "Relax, Spa, Meditation, Nature, Space",
  },
  {
    id: "music-26",
    name: "Leva - Eternity",
    author: "lemonmusicstudio",
    url: "https://cdn.designcombo.dev/music/audio_5198c12188.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 144,
    alt: "Acoustic, Folk, Summer, Love, Family",
  },
  {
    id: "music-27",
    name: "Forest Lullaby",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_1395e7800f.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 138,
    alt: "Lullaby, Nature, Relax, Acoustic, Guitar",
  },
  {
    id: "music-28",
    name: "Silent Evening (Calm Piano)",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_9f1cf4cc49.mp3",
    category: "music",
    genre: "modern classical",
    duration: 310,
    alt: "Relaxing Piano, Calm Piano Music",
  },
  {
    id: "music-29",
    name: "Emotional Piano Background Music",
    author: "SigmaMusicArt",
    url: "https://cdn.designcombo.dev/music/audio_e638f62051.mp3",
    category: "music",
    genre: "modern classical",
    duration: 108,
    alt: "Piano, Calm, Soft, Relax, Instrumental",
  },
  {
    id: "music-30",
    name: "Summer Walk",
    author: "folk_acoustic",
    url: "https://cdn.designcombo.dev/music/audio_cbcfcb18e6.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 197,
    alt: "Indie, Folk, Acoustic, Singer-Songwriter",
  },
  {
    id: "music-31",
    name: "Cinematic Documentary",
    author: "Lexin_Music",
    url: "https://cdn.designcombo.dev/music/audio_ed0c111294.mp3",
    category: "music",
    genre: "beautiful plays",
    duration: 131,
    alt: "Travel, Beautiful, Cinematic, Discovery",
  },
  {
    id: "music-32",
    name: "Inspiring Piano Music",
    author: "ProductionMusic",
    url: "https://cdn.designcombo.dev/music/audio_ce9cea9ea9.mp3",
    category: "music",
    genre: "modern classical",
    duration: 108,
    alt: "Piano, Inspiring, Calm, Soft, Valentines",
  },
  {
    id: "music-33",
    name: "Sedative",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_30ff2fdf22.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 181,
    alt: "Sedative, Sedative Music",
  },
  {
    id: "music-34",
    name: "Ambient Piano and Strings",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_cb4f1212a9.mp3",
    category: "music",
    genre: "beautiful plays",
    duration: 217,
    alt: "SOTIFY:https://bit.ly/Spotify_Zakhar_Valaha",
  },
  {
    id: "music-35",
    name: "Piano Moment",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_05570f2464.mp3",
    category: "music",
    genre: "solo piano",
    duration: 273,
    alt: "Ambient, Background, Beautiful, Calm",
  },
  {
    id: "music-36",
    name: "A Small Miracle",
    author: "Romarecord1973",
    url: "https://cdn.designcombo.dev/music/audio_d74b2d0ff4.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 76,
    alt: "Acoustic, Ukulele, Light, Mellow, Serene",
  },
  {
    id: "music-37",
    name: "A call to the soul",
    author: "folk_acoustic_music",
    url: "https://cdn.designcombo.dev/music/audio_3dc71287de.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 159,
    alt: "Folk, Acoustic, Guitar, Ambient, Nature",
  },
  {
    id: "music-38",
    name: "Il Tempo Lento Delle Onde (Instrumental)",
    author: "ImagoSonora",
    url: "https://cdn.designcombo.dev/music/audio_3d70f84f43.mp3",
    category: "music",
    genre: "ambient",
    duration: 327,
    alt: "Ambient, Ambient Music, Meditation",
  },
  {
    id: "music-39",
    name: "relaxing piano music",
    author: "Clavier-Music",
    url: "https://cdn.designcombo.dev/music/audio_7131602177.mp3",
    category: "music",
    genre: "modern classical",
    duration: 127,
    alt: "Calm, Soft, Piano, Relax, Piano Music",
  },
  {
    id: "music-40",
    name: "Morning Garden - Acoustic Chill",
    author: "folk_acoustic",
    url: "https://cdn.designcombo.dev/music/audio_ea75bab6d8.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 233,
    alt: "Acoustic, Guitar, Relax, Relaxation",
  },
  {
    id: "music-41",
    name: "Silent Night_Medium 1",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_3bed0e2164.mp3",
    category: "music",
    genre: "christmas",
    duration: 153,
    alt: "An emotional, gentle royalty-free Silent Night version, with acoustic guitar, symphony orchestra, and bells, ideal for films, ads, kids or lovely Xmas contents.",
  },
  {
    id: "music-42",
    name: "Deep Relaxation Meditation. Nervous System Healing",
    author: "White_Records",
    url: "https://cdn.designcombo.dev/music/audio_6bf2bfe5be.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 390,
    alt: "Background Music, Yoga Music",
  },
  {
    id: "music-43",
    name: "Inspiring Cinematic Background Music For Videos",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_6d7cd70222.mp3",
    category: "music",
    genre: "build up scenes",
    duration: 210,
    alt: "",
  },
  {
    id: "music-44",
    name: "Piano Music No.14",
    author: "RelaxingTime",
    url: "https://cdn.designcombo.dev/music/audio_3a91a153a1.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 1421,
    alt: "Music, Piano, Music For Movies, Peaceful",
  },
  {
    id: "music-45",
    name: "Christian Instrumental Piano Worship Calm Emotional Soaking Prayer",
    author: "JesseQuinnMedia",
    url: "https://cdn.designcombo.dev/music/audio_83d4314085.mp3",
    category: "music",
    genre: "ambient",
    duration: 229,
    alt: "Christian, Instrumental, Piano, Worship",
  },
  {
    id: "music-46",
    name: "Melody of Nature (Main)",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_88447e769f.mp3",
    category: "music",
    genre: "beautiful plays",
    duration: 181,
    alt: "Nature, Violin, Beauty, China, Japan",
  },
  {
    id: "music-47",
    name: "Simple Piano Melody",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_47edc456e3.mp3",
    category: "music",
    genre: "modern classical",
    duration: 91,
    alt: "Background, Bright, Business, Confidence",
  },
  {
    id: "music-48",
    name: "Healing Meditation Ringing Background Music For Meditation",
    author: "White_Records",
    url: "https://cdn.designcombo.dev/music/audio_86b494f3a6.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 364,
    alt: "Background Music, Ambient Music",
  },
  {
    id: "music-49",
    name: "THE WAY HOME",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_c9a4a1d834.mp3",
    category: "music",
    genre: "modern classical",
    duration: 226,
    alt: "Violin, Piano, Sad, Nature, Flowers",
  },
  {
    id: "music-50",
    name: "Spa Ambient (10min)",
    author: "Rockot",
    url: "https://cdn.designcombo.dev/music/audio_1778340e01.mp3",
    category: "music",
    genre: "ambient",
    duration: 600,
    alt: "Spa Music, Ambient Music, Relaxing Music",
  },
  {
    id: "music-51",
    name: "Documentary_Tidal",
    author: "Coma-Media",
    url: "https://cdn.designcombo.dev/music/audio_9d5564262c.mp3",
    category: "music",
    genre: "ambient",
    duration: 137,
    alt: "Surrounding, Atmosphere, Background",
  },
  {
    id: "music-52",
    name: "Freedom Inspired Cinematic Background Music For Video",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_9584aae297.mp3",
    category: "music",
    genre: "trap",
    duration: 140,
    alt: "",
  },
  {
    id: "music-53",
    name: "instrumental,  ambient,  calming",
    author: "Huynhhoa89",
    url: "https://cdn.designcombo.dev/music/audio_57d9cca8d7.mp3",
    category: "music",
    genre: "ambient",
    duration: 240,
    alt: "Instrumental, Calming, Nature, Peaceful",
  },
  {
    id: "music-54",
    name: "AMBIENT PIANO x RELAXING prod. by BlackPyBeats",
    author: "BlackPyBeats",
    url: "https://cdn.designcombo.dev/music/audio_5131486aba.mp3",
    category: "music",
    genre: "solo piano",
    duration: 625,
    alt: "Happy, Smile, Music, Strings, Relax",
  },
  {
    id: "music-55",
    name: "Where the Light is",
    author: "lemonmusicstudio",
    url: "https://cdn.designcombo.dev/music/audio_8ae38e1c91.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 128,
    alt: "Love, Folk, Family, Inspiring",
  },
  {
    id: "music-56",
    name: "Silent Night_Medium 2",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_6317edc014.mp3",
    category: "music",
    genre: "christmas",
    duration: 84,
    alt: "An emotional, gentle royalty-free Silent Night version, with acoustic guitar, symphony orchestra, and bells, ideal for films, ads, kids or lovely Xmas contents.",
  },
  {
    id: "music-57",
    name: "Canción Triste",
    author: "enrique27naveda",
    url: "https://cdn.designcombo.dev/music/audio_547ebbf828.mp3",
    category: "music",
    genre: "suspense",
    duration: 471,
    alt: "",
  },
  {
    id: "music-58",
    name: "My Love_34sec",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_c526b58143.mp3",
    category: "music",
    genre: "wedding",
    duration: 35,
    alt: "«My Love» is a very beautiful, inspirational, romantic, sentimental and emotional background music in cinematic style. Perfect for videos, films, documentaries, cinematic scenes, inspirational, poetry, spoken, podcasts, weddings, TV and radio shows, advertising and marketing.",
  },
  {
    id: "music-59",
    name: "Flying In The Dream (A Meditation)",
    author: "Ashot_Danielyan",
    url: "https://cdn.designcombo.dev/music/audio_38be17baf6.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 489,
    alt: "Advertising, Ambient, Atmospheric",
  },
  {
    id: "music-60",
    name: "Silent Night_60sec",
    author: "Grand_Project",
    url: "https://cdn.designcombo.dev/music/audio_3241306cbb.mp3",
    category: "music",
    genre: "christmas",
    duration: 60,
    alt: "An emotional, gentle royalty-free Silent Night version, with acoustic guitar, symphony orchestra, and bells, ideal for films, ads, kids or lovely Xmas contents.",
  },
  {
    id: "music-61",
    name: "Shooting stars",
    author: "Piano_Music",
    url: "https://cdn.designcombo.dev/music/audio_fd61700c9e.mp3",
    category: "music",
    genre: "solo piano",
    duration: 128,
    alt: "Piano, Classical, Piano Music",
  },
  {
    id: "music-62",
    name: "Relax in the Forest background music for video",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_52143d4cea.mp3",
    category: "music",
    genre: "ambient",
    duration: 195,
    alt: "Relax, Relaxing, Relaxation, Ambient",
  },
  {
    id: "music-63",
    name: "Chilled Acoustic Indie Folk Instrumental Background Music For Videos",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_6623aaf984.mp3",
    category: "music",
    genre: "beautiful plays",
    duration: 140,
    alt: "",
  },
  {
    id: "music-64",
    name: "Inspiring Documentary Background",
    author: "JoyInSound",
    url: "https://cdn.designcombo.dev/music/audio_ccb16202da.mp3",
    category: "music",
    genre: "solo piano",
    duration: 96,
    alt: "Documentary, Ambient, Cinematic",
  },
  {
    id: "music-65",
    name: "Angelic Meditation",
    author: "35433346",
    url: "https://cdn.designcombo.dev/music/audio_6326a3d340.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 891,
    alt: "Relaxation, Atmospheric, Music",
  },
  {
    id: "music-66",
    name: "Background Music for Nature",
    author: "SoundGalleryByDmitryTaras",
    url: "https://cdn.designcombo.dev/music/audio_0cde46a259.mp3",
    category: "music",
    genre: "ambient",
    duration: 126,
    alt: "Background Music, Music, Background",
  },
  {
    id: "music-67",
    name: "My Life (Main)",
    author: "Good_B_Music",
    url: "https://cdn.designcombo.dev/music/audio_6eb9c39740.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 118,
    alt: "Acoustic, Guitar, Inspiration",
  },
  {
    id: "music-68",
    name: "Hindi Inspire",
    author: "Waveloom",
    url: "https://cdn.designcombo.dev/music/audio_15e3b462f9.mp3",
    category: "music",
    genre: "india",
    duration: 219,
    alt: "Music, Instrumental, Advertising",
  },
  {
    id: "music-69",
    name: "Historical Documentary Background - Atmospheric Moments",
    author: "SigmaMusicArt",
    url: "https://cdn.designcombo.dev/music/audio_1bf176d700.mp3",
    category: "music",
    genre: "modern classical",
    duration: 85,
    alt: "Documentary, History, Background",
  },
  {
    id: "music-70",
    name: "Bathroom - Chill Background Music",
    author: "chill_background",
    url: "https://cdn.designcombo.dev/music/audio_d3a7b18ab3.mp3",
    category: "music",
    genre: "ambient",
    duration: 240,
    alt: "Chill, Music, Lofi, Guitar, Relax",
  },
  {
    id: "music-71",
    name: "Worship Piano Instrumental Peaceful Prayer Music",
    author: "Denis-Pavlov-Music",
    url: "https://cdn.designcombo.dev/music/audio_19e3c81cb3.mp3",
    category: "music",
    genre: "modern classical",
    duration: 584,
    alt: "Worship, Christian, Spiritual, Religion",
  },
  {
    id: "music-72",
    name: "Sacred Sound",
    author: "Aonescape",
    url: "https://cdn.designcombo.dev/music/audio_2ef63979d4.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 103,
    alt: "Calm, Relax, Meditate, Mindfulness, Zen",
  },
  {
    id: "music-73",
    name: "Flight of your Muse - Background Music For Meditation",
    author: "White_Records",
    url: "https://cdn.designcombo.dev/music/audio_7e90fd4bf7.mp3",
    category: "music",
    genre: "meditation/spiritual",
    duration: 431,
    alt: "Relax, Spa, Yoga Music, Relaxation Music",
  },
  {
    id: "music-74",
    name: "Nature Calls",
    author: "folk_acoustic",
    url: "https://cdn.designcombo.dev/music/audio_384c4a93a5.mp3",
    category: "music",
    genre: "acoustic group",
    duration: 180,
    alt: "Nature, Guitar, Acoustic",
  },
  {
    id: "music-75",
    name: 'Chillhop Beat "Thousand Miles"',
    author: "Music_Unlimited",
    url: "https://cdn.designcombo.dev/music/audio_25a6306c10.mp3",
    category: "music",
    genre: "beats",
    duration: 115,
    alt: "Chillhop, Hip Hop, Chill, Ambient, Lofi",
  },
  {
    id: "music-76",
    name: "Lost Ambient Lofi 60s",
    author: "music_for_video",
    url: "https://cdn.designcombo.dev/music/audio_90fbff7b5d.mp3",
    category: "music",
    genre: "beats",
    duration: 58,
    alt: "Background Music, Lofi, Lofi Hip Hop",
  },
  {
    id: "music-77",
    name: "Soft ambient",
    author: "Alex_MakeMusic",
    url: "https://cdn.designcombo.dev/music/audio_32f870cd15.mp3",
    category: "music",
    genre: "modern classical",
    duration: 192,
    alt: "Piano, Ambient, Night, Soft, Love",
  },
  {
    id: "music-78",
    name: "Calm Relaxing Ambient – Peaceful Background Music",
    author: "Clavier-Music",
    url: "https://cdn.designcombo.dev/music/audio_d5cf77920e.mp3",
    category: "music",
    genre: "ambient",
    duration: 128,
    alt: "Calm, Relaxing, Ambient, Peaceful, Soft",
  },
  {
    id: "music-79",
    name: "God is Always With Me",
    author: "Silentvoice",
    url: "https://cdn.designcombo.dev/music/audio_e9e87b8c2c.mp3",
    category: "music",
    genre: "ambient",
    duration: 499,
    alt: "God, Relax, Prayer, Background Music",
  },
  {
    id: "music-80",
    name: "Beautiful Worship Piano Peaceful Music",
    author: "Denis-Pavlov-Music",
    url: "https://cdn.designcombo.dev/music/audio_8749b96bc6.mp3",
    category: "music",
    genre: "modern classical",
    duration: 510,
    alt: "Worship, Praise, Prayer, Piano, Music",
  },
];
