import { GoogleGenAI } from "@google/genai";
import { NextResponse } from "next/server";
import { kie } from "@/lib/kie";
import { R2StorageService } from "@/lib/r2-storage";
import { generateId } from "@/utils/id";
import { config } from "@/inngest/config";
import { ImageGenerator } from "@/lib/image-generation";
const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;

export async function POST(req: Request) {
  try {
    if (!apiKey) {
      return NextResponse.json(
        { error: "GOOGLE_GENERATIVE_AI_API_KEY is not defined" },
        { status: 500 },
      );
    }

    const { description, aspectRatio = "9:16" } = await req.json();

    if (!description) {
      return NextResponse.json({ error: "Description is required" }, { status: 400 });
    }

    const genAI = new GoogleGenAI({ apiKey });
    const model = "gemini-2.5-flash-lite";

    const promptExpansionText = `You are a world-class AI prompt engineer specializing in authentic UGC (User Generated Content) aesthetics. 
    Your goal is to expand a simple avatar description into a hyper-realistic image generation prompt that looks like a real person recorded it on their phone or a casual camera setup.

    **Simple Description:** ${description}

    **Requirements for the Expanded Prompt:**
    1. **Hyper-Realistic & Relatable Appearance:** Describe unique, non-perfect facial features. Focus on authentic skin textures, natural hair, and realistic eye contact. Avoid "plastic" or over-perfected AI looks. 
    2. **Authentic UGC Environments:** Place the avatar in a specific, lived-in location. Examples for inspiration:
       - Sitting in a car driver's seat (natural sunlight from the window).
       - At a desk with a podcast microphone, notebooks, or a coffee mug.
       - In a library or study area wearing headphones, leaning over a book.
       - On a balcony or outdoor deck with a natural, slightly messy background.
       - In a gym, standing near weights or on a bench.
       - In a grocery store aisle or a busy cafe.
    3. **Natural & Varied Lighting:** Use realistic lighting scenarios—harsh dappled sunlight through a car window, overhead office fluorescent lights, soft natural window light, or warm indoor ambient glow.
    4. **Camera & Framing:** Mimic a phone camera or a casual vlogging setup. Use keywords like "shot on iPhone", "vlog style", "slight handheld motion blur (subtle)", "24mm or 35mm lens", "eye-level or slightly high selfie-angle".
    5. **Styling & Props:** Clothing should be casual and "real" (hoodies, t-shirts, blazers, workout gear). Include relevant props: sunglasses, headphones, lapel mics, podcast mics, pens, or drinks.
    6. **NO TEXT/UI:** Absolutely no text, labels, watermarks, or UI elements.
    7. **Vibe:** The person should look approachable, authentic, and caught-in-the-moment, ready to speak directly to the camera.

    Return ONLY the expanded prompt text.`;

    const result = await genAI.models.generateContent({
      model,
      contents: [{ text: promptExpansionText }],
    });
    const expandedPrompt = result.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";

    console.log("Expanded Prompt:", expandedPrompt);

    const imageGenerator = new ImageGenerator({
      provider: "gemini",
      params: {
        apiKey: config.gemini.key,
        model: config.gemini.imageModel,
      },
    });

    const base64Image = await imageGenerator.create({
      prompt: expandedPrompt,
      aspectRatio,
    });

    if (!base64Image) {
      return NextResponse.json(
        { error: "No image generated by Nano Banana (v2)" },
        { status: 500 },
      );
    }

    // Convert base64 to Buffer
    const buffer = Buffer.from(base64Image, "base64");

    const storage = new R2StorageService({
      bucketName: config.r2.bucket,
      accessKeyId: config.r2.accessKeyId,
      secretAccessKey: config.r2.secretAccessKey,
      accountId: config.r2.accountId,
      cdn: config.r2.cdn,
    });

    const storageUrl = await storage.uploadData(`VIDEOS/avatars/${generateId()}.png`, buffer);

    const data = {
      data: {
        url: storageUrl,
        recordId: "nano-banana-direct",
      },
    };

    console.log("Image Task Data:", data);
    return NextResponse.json({ ...data, expandedPrompt }, { status: 200 });
  } catch (error: any) {
    console.error("Error in /api/avatar/generate:", error);
    return NextResponse.json(
      { error: "Internal Server Error", details: error.message },
      { status: 500 },
    );
  }
}
