import fs from "fs";
import os from "os";
import { nanoid } from "nanoid";
import { db } from "@/lib/database";
import { segmentQueries } from "@/lib/database/segment-queries";
import { UgcServices } from "../index";
import { getBRollDisplayTime } from "../../common/steps";
import { downloadVideo, fileUrlToBuffer } from "../../common/utils/common";
import { aspectRatioType } from "@/utils/enum";

export const generateSegmentBRolls = async (
  segmentResult: any,
  schema: any,
  projectId: string,
  services: UgcServices,
) => {
  const r2 = services.r2;
  const segmentData = segmentResult.segment_data as any;
  const captionUrl = (segmentResult as any).captionUrl;
  if (!captionUrl) return null;

  const bRolls = segmentData.bRolls || [];
  if (bRolls.length === 0) return null;

  const newBRollAssets: any[] = [];
  const processedBRolls: any[] = [];

  for (const bRoll of bRolls) {
    try {
      const dataTime = await getBRollDisplayTime(bRoll.words, captionUrl, 0);
      console.log({ dataTime });
      if (dataTime && dataTime.display) {
        // firstFrame is now a descriptive image generation prompt generated by the AI
        const imageGenerationPrompt =
          bRoll.firstFrame || bRoll.scenePrompt || bRoll.videoPrompt || "";

        const bRollAssetUrls: string[] = (schema.assets || [])
          .filter((a: any) => a.type === "image")
          .map((a: any) => a.url);

        const firstFrameUrl = await services.imageGenerator.create({
          prompt: imageGenerationPrompt,
          aspectRatio: (schema.aspect_ratio as aspectRatioType) || aspectRatioType.NINE_SIXTEEN,
          imageUrls: bRollAssetUrls,
        });

        const { buffer, extension } = await fileUrlToBuffer(firstFrameUrl);
        const imagePath = `projects/${projectId}/images/${segmentResult.id}-bRoll-${nanoid(5)}.${extension}`;
        const avatarImageUrl = await r2.uploadData(imagePath, buffer);

        const pixversePrompt =
          `${bRoll.videoPrompt || ""} Subtle handheld camera micro-tremors, natural lighting, organic feel.`.trim();

        const bRollResult = await services.videoGenerator.create({
          prompt: pixversePrompt,
          style: schema.visuals?.style,
          firstFrameUrl: avatarImageUrl,
          durationSeconds: 5,
        });

        const bRollVideoUrl = typeof bRollResult === "string" ? bRollResult : bRollResult.url;

        if (bRollVideoUrl) {
          const tmpDir = os.tmpdir();
          const bRollPath = await downloadVideo(bRollVideoUrl, tmpDir);
          const finalBRollUrl = await r2.uploadData(
            `projects/${projectId}/videos/${segmentResult.id}-bRoll-${nanoid(5)}.mp4`,
            fs.readFileSync(bRollPath),
            "video/mp4",
          );

          const startTimeMs = Math.round(dataTime.display.from);
          const bRollDurationMs = Math.round(dataTime.display.to - dataTime.display.from);

          const bRollDisplayMs = {
            from: startTimeMs,
            to: startTimeMs + bRollDurationMs,
          };

          newBRollAssets.push({
            id: nanoid(),
            type: "video",
            category: "b-roll",
            url: finalBRollUrl,
            status: "completed",
            active: true,
            metadata: bRoll,
            display: bRollDisplayMs,
          });

          processedBRolls.push({
            ...bRoll,
            videoUrl: finalBRollUrl,
            type: "video",
            time: startTimeMs,
            duration: bRollDurationMs,
            display: bRollDisplayMs,
          });
        }
      }
    } catch (err) {
      console.error(`Failed to generate B-Roll for segment ${segmentResult.id}:`, err);
    }
  }

  if (newBRollAssets.length > 0) {
    const latestSegment = await segmentQueries.findSegmentById(segmentResult.id);
    if (latestSegment) {
      const latestData = latestSegment.segment_data as any;

      const updatedAssets = (latestData.assets || []).filter((a: any) => a.category !== "b-roll");

      const updatedShots = updatedAssets.filter((a: any) => a.active);

      const { bRolls: _obr, ...latestDataWithoutBRolls } = latestData;

      const updatedSegmentData = {
        ...latestDataWithoutBRolls,
        assets: updatedAssets,
        shots: updatedShots,
        bRolls: processedBRolls,
      };

      await db
        .updateTable("segments")
        .set({ segment_data: updatedSegmentData })
        .where("id", "=", segmentResult.id)
        .execute();

      return { id: segmentResult.id, generated: newBRollAssets.length };
    }
  }
  return null;
};

export const generateUgcBrollVideo = async ({
  segment,
  bRoll,
  projectId,
  schemaId,
  services,
  runToken,
}: {
  segment: any;
  bRoll: any;
  projectId: string;
  schemaId: string;
  services: UgcServices;
  runToken: string;
}) => {
  const { r2, videoGenerator } = services;
  const segmentData = segment.segment_data as any;
  const captionUrl = segmentData.speechToText?.src;

  if (!captionUrl) {
    console.warn(`[B-Roll] No captionUrl found for segment ${segment.id}. Skipping B-roll.`);
    return null;
  }

  const dataTime = await getBRollDisplayTime(bRoll.words, captionUrl, 0);
  if (!dataTime || !dataTime.display) {
    console.warn(
      `[B-Roll] Could not find timing for words "${bRoll.words}" in segment ${segment.id}.`,
    );
    return null;
  }

  const bRollResult = await videoGenerator.create({
    prompt: bRoll.videoPrompt || "",
    style: "Cinematic",
    aspectRatio: "9:16",
    durationSeconds: 5,
    firstFrameUrl: bRoll.firstFrame, // AI generated prompt or URL
  });

  const videoUrl = typeof bRollResult === "string" ? bRollResult : bRollResult.url;

  if (videoUrl) {
    const tmpDir = os.tmpdir();
    const bRollPath = await downloadVideo(videoUrl, tmpDir);
    const finalBRollUrl = await r2.uploadData(
      `ugc-videos/${schemaId}/${segment.id}/broll-${nanoid(5)}.mp4`,
      fs.readFileSync(bRollPath),
      "video/mp4",
    );

    const updatedBroll = {
      ...bRoll,
      videoUrl: finalBRollUrl,
      type: "video",
      display: dataTime.display,
    };

    await updateSegmentBroll(segment.id, updatedBroll);
    return updatedBroll;
  }

  return null;
};

export const generateUgcBrollImage = async ({
  segment,
  bRoll,
  projectId,
  schemaId,
  services,
  model = "gemini-3.1-flash-image-preview",
}: {
  segment: any;
  bRoll: any;
  projectId: string;
  schemaId: string;
  services: UgcServices;
  model?: string;
}) => {
  const { r2, imageGenerator } = services;
  const segmentData = segment.segment_data as any;
  const captionUrl = segmentData.speechToText?.src;

  if (!captionUrl) {
    console.warn(`[Overlay] No captionUrl found for segment ${segment.id}. Skipping overlay.`);
    return null;
  }

  const dataTime = await getBRollDisplayTime(bRoll.words, captionUrl, 0);
  if (!dataTime || !dataTime.display) {
    console.warn(
      `[Overlay] Could not find timing for words "${bRoll.words}" in segment ${segment.id}.`,
    );
    return null;
  }

  console.log(`[Overlay] Generating image for segment ${segment.id} using model: ${model}...`);
  // Ensure strict style constraints are prepended to the prompt
  const stylePrefix =
    "Professional, cinematic, realistic UGC diagnostic graphic. High quality, photorealistic, NO text, NO labels, NO UI elements. Shot-on-iPhone aesthetic. ";
  const finalPrompt = stylePrefix + (bRoll.firstFrame || bRoll.videoPrompt || "");

  const resultBase64 = await imageGenerator.create({
    prompt: finalPrompt,
    model,
    aspectRatio: aspectRatioType.ONE,
  });

  if (!resultBase64) {
    throw new Error(`[Overlay] Image generation returned empty data for segment ${segment.id}`);
  }

  const cleanBase64 = resultBase64.replace(/^data:image\/\w+;base64,/, "");
  const buffer = Buffer.from(cleanBase64, "base64");

  if (buffer.length === 0) {
    throw new Error(`[Overlay] Image buffer is empty for segment ${segment.id}`);
  }

  const extension = "png";
  const imagePath = `ugc-videos/${schemaId}/${segment.id}/overlay-${nanoid(5)}.${extension}`;
  const finalImageUrl = await r2.uploadData(imagePath, buffer, "image/png");
  console.log(`[Overlay] Image generated and uploaded: ${finalImageUrl}`);

  const updatedOverlay = {
    ...bRoll,
    imageUrl: finalImageUrl,
    type: "image",
    display: dataTime.display,
  };

  await updateSegmentBroll(segment.id, updatedOverlay);
  return updatedOverlay;
};

async function updateSegmentBroll(segmentId: string, bRoll: any) {
  const segment = await db
    .selectFrom("segments")
    .select("segment_data")
    .where("id", "=", segmentId)
    .executeTakeFirst();

  if (!segment) return;

  const data = segment.segment_data as any;
  const bRolls = (data.bRolls || []) as any[];

  // Update or append the bRoll
  const existingIndex = bRolls.findIndex(
    (b) => b.words === bRoll.words && b.displayMode === bRoll.displayMode,
  );
  if (existingIndex > -1) {
    bRolls[existingIndex] = bRoll;
  } else {
    bRolls.push(bRoll);
  }

  // Also update assets array for rendering
  const assetId = nanoid();
  const mediaUrl = bRoll.videoUrl || bRoll.imageUrl || bRoll.url;
  const updatedAssets = [
    ...(data.assets || []),
    {
      id: assetId,
      type: bRoll.type,
      category: "b-roll",
      url: mediaUrl,
      status: "completed",
      active: true,
      display: bRoll.display,
      metadata: bRoll,
    },
  ];

  await db
    .updateTable("segments")
    .set({
      segment_data: {
        ...data,
        bRolls,
        assets: updatedAssets,
      },
    })
    .where("id", "=", segmentId)
    .execute();
}
